library(devtools)
library(roxygen2)
library(usethis)
file.remove("NAMESPACE")
usethis::use_apache_license()
devtools::document()
devtools::check()
remove.packages("xplot")
devtools::install()
## Commit Push
# remotes::install_github("averriK/xplot",auth_token = Sys.getenv("PAT"))
